<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import ElMessage from 'element-plus/es/components/message/index'
import { downloadGeneratedCode, fetchCodePreview, fetchCodegenTables, type CodePreview, type CodegenTable } from './api-client'
import { usePermissionStore } from './permission-store'
const permissions=usePermissionStore();const loading=ref(false);const tables=ref<CodegenTable[]>([]);const selected=ref('');const moduleName=ref('');const preview=ref<CodePreview|null>(null);const selectedFile=ref('')
const subject=computed(()=>import.meta.env.DEV?permissions.demoSubject||undefined:undefined);const canExport=computed(()=>permissions.can('code-generation','EXPORT'))
const currentFile=computed(()=>preview.value?.files.find(file=>file.path===selectedFile.value)??null)
async function load(){loading.value=true;try{tables.value=await fetchCodegenTables(subject.value);if(!selected.value&&tables.value.length){selected.value=tables.value[0].tableName;moduleName.value=defaultModule(selected.value)}}catch(reason){ElMessage.error(error(reason,'数据表读取失败'))}finally{loading.value=false}}
async function generate(){if(!selected.value)return;loading.value=true;try{preview.value=await fetchCodePreview(subject.value,selected.value,moduleName.value);selectedFile.value=preview.value.files[0]?.path??''}catch(reason){ElMessage.error(error(reason,'代码预览失败'))}finally{loading.value=false}}
async function download(){try{await downloadGeneratedCode(subject.value,selected.value,moduleName.value)}catch(reason){ElMessage.error(error(reason,'代码下载失败'))}}
function choose(table:CodegenTable){selected.value=table.tableName;moduleName.value=defaultModule(table.tableName);preview.value=null}
function defaultModule(table:string){return table.replace(/^(coreib_|sys_|biz_)/i,'').replaceAll('_','-')}
function error(reason:unknown,fallback:string){return reason instanceof Error?`${fallback}：${reason.message}`:fallback}
onMounted(load)
</script>
<template><section class="page-view"><div class="page-heading compact-heading"><div><h1>代码生成</h1><p>从当前数据库元数据生成 Spring JDBC、REST API、Vue3 页面、TypeScript API 和 Liquibase 迁移草稿。</p></div><div class="codegen-actions"><el-button type="primary" :disabled="!selected" :loading="loading" @click="generate">生成预览</el-button><el-button v-if="canExport" :disabled="!preview" @click="download">下载 ZIP</el-button></div></div><div class="codegen-layout"><section class="surface-panel codegen-tables"><div class="panel-title"><strong>数据库表</strong><el-button size="small" :loading="loading" @click="load">刷新</el-button></div><button v-for="table in tables" :key="`${table.schema}.${table.tableName}`" type="button" class="codegen-table" :class="{active:selected===table.tableName}" @click="choose(table)"><span><strong>{{table.tableName}}</strong><small>{{table.schema||'DEFAULT'}} · {{table.columnCount}} 字段</small></span></button><el-empty v-if="!tables.length&&!loading" description="未发现业务表"/></section><section class="surface-panel codegen-workspace"><div class="codegen-config"><el-form label-width="80px"><el-form-item label="数据表"><el-input v-model="selected" disabled/></el-form-item><el-form-item label="模块名"><el-input v-model="moduleName" placeholder="patient-record"/></el-form-item></el-form></div><template v-if="preview"><el-tabs v-model="selectedFile" class="code-tabs"><el-tab-pane v-for="file in preview.files" :key="file.path" :label="file.path.split('/').at(-1)" :name="file.path"/></el-tabs><pre class="code-preview"><code>{{currentFile?.content}}</code></pre><div class="column-metadata"><el-tag v-for="column in preview.columns" :key="column.name" effect="plain">{{column.name}} · {{column.javaType}}{{column.primaryKey?' · PK':''}}</el-tag></div></template><el-empty v-else description="选择数据表并生成预览"/></section></div></section></template>
