<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import ElMessage from 'element-plus/es/components/message/index'
import { fetchAuditEvents, fetchLoginEvents, type AuditEvent, type LoginEvent } from './api-client'
import { usePermissionStore } from './permission-store'
const route=useRoute();const permissions=usePermissionStore();const loading=ref(false);const search=ref('');const rows=ref<(AuditEvent|LoginEvent)[]>([])
const kind=computed(()=>route.meta.logKind as 'audit'|'login');const subject=computed(()=>import.meta.env.DEV?permissions.demoSubject||undefined:undefined)
const filtered=computed(()=>{const key=search.value.toLowerCase().trim();return key?rows.value.filter(row=>JSON.stringify(row).toLowerCase().includes(key)):rows.value})
async function load(){loading.value=true;try{rows.value=kind.value==='audit'?await fetchAuditEvents(subject.value):await fetchLoginEvents(subject.value)}catch(reason){ElMessage.error(reason instanceof Error?`日志读取失败：${reason.message}`:'日志读取失败')}finally{loading.value=false}}
function time(value:string){return value?new Date(value).toLocaleString('zh-CN'):'-'}
watch(kind,load);onMounted(load)
</script>
<template><section class="page-view"><div class="page-heading compact-heading"><div><h1>{{ route.meta.title }}</h1><p>{{ kind==='audit'?'查询平台关键操作的执行人、资源、结果和发生时间。':'查询身份认证、平台主体解析和访问来源。' }}</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><section class="surface-panel management-toolbar"><el-input v-model="search" clearable placeholder="搜索日志"/><span class="record-count">共 {{ filtered.length }} 条</span></section><section class="surface-panel" v-loading="loading"><el-table v-if="kind==='audit'" :data="filtered" stripe><el-table-column prop="actorId" label="操作人" min-width="150"/><el-table-column prop="action" label="动作" width="100"/><el-table-column prop="resource" label="资源" min-width="150"/><el-table-column prop="targetId" label="目标" min-width="160"/><el-table-column label="结果" width="100"><template #default="scope"><el-tag :type="scope.row.outcome==='SUCCESS'?'success':'danger'">{{scope.row.outcome}}</el-tag></template></el-table-column><el-table-column prop="details" label="详情" min-width="220" show-overflow-tooltip/><el-table-column label="时间" min-width="180"><template #default="scope">{{time(scope.row.occurredAt)}}</template></el-table-column></el-table><el-table v-else :data="filtered" stripe><el-table-column prop="userId" label="平台用户" min-width="160"/><el-table-column prop="identityName" label="身份" min-width="160"/><el-table-column prop="sourceIp" label="来源地址" min-width="140"/><el-table-column label="结果" width="110"><template #default="scope"><el-tag :type="scope.row.outcome==='SUCCESS'?'success':'info'">{{scope.row.outcome}}</el-tag></template></el-table-column><el-table-column prop="message" label="认证模式" min-width="140"/><el-table-column label="时间" min-width="180"><template #default="scope">{{time(scope.row.occurredAt)}}</template></el-table-column></el-table></section></section></template>
